Repository website-checks/website-checks, pull requests merged in 2020-10, with the labels that each got.

#64 Add yellowlab.tools check (fixes #63)
  index.js
  modules/checks.js
  modules/checks/yellowlab.js
  package.json
Labels: Hacktoberfest, enhancement

#66 Append yellowlab check README
  README.md
Labels: Hacktoberfest

#65 Add CI yellowlab check
  .github/workflows/main.yml
Labels: Hacktoberfest

#61 Enable strict mode - closes #57
  modules/check-function.js
  modules/checks.js
  modules/checks/check-your-website.js
  modules/checks/crtsh.js
  modules/checks/cryptcheck.js
  modules/checks/hstspreload.js
  modules/checks/httpobservatory.js
  modules/checks/lighthouse.js
  modules/checks/psi.js
  modules/checks/securityheaders.js
  modules/checks/ssldecoder.js
  modules/checks/ssllabs.js
  modules/checks/webbkoll.js
  modules/checks/webhint.js
  modules/checks/yellowlab.js
  modules/cli-help.js
  modules/create-datetime-string.js
  modules/create-folders.js
  modules/error-handler.js
  modules/retry.js
  modules/set-output.js
  modules/setup.js
  modules/success-handler.js
  modules/teardown.js
  modules/url-check.js
  utils/process-argv.js
Labels: enhancement
